### ISSUE TITLE
Ability to follow specific users

### ISSUE THREAD

**Issue by jasonrhaas** [logstash-plugins/logstash-input-twitter#25] opened 2015-08-21 22:26 UTC
Would be nice to implement the "follow" parameter in the Public Twitter API.  Implementing the "follow" parameter would allow the user to add a list of twitter user ids and collect tweets from those ids.

https://dev.twitter.com/streaming/overview/request-parameters#follow

**Comment by acchen97** [comment] 2015-11-09 18:56
Duplicate of https://github.com/logstash-plugins/logstash-input-twitter/issues/11

**Comment by purbon** [comment] 2015-11-10 06:35
Closing this as duplicate of #11

**Closed by purbon** 2015-11-10 06:35 UTC
