### ISSUE TITLE
Add "sample" endpoint support for twitter inputs

### ISSUE THREAD

**Issue by untergeek** [logstash-plugins/logstash-input-twitter#6] opened 2015-01-23 20:03 UTC
Migrated from https://github.com/elasticsearch/logstash/issues/1620  
Please see that issue for the ensuing discussion.

**Comment by dadoonet** [comment] 2015-04-02 15:19
+1 would be awesome for test purpose

**Comment by purbon** [comment] 2015-11-10 06:41
duplicate of #21 closing this and moving all discussion to the other issue.

**Closed by purbon** 2015-11-10 06:41 UTC
Labels: enhancement
